FROM ubuntu:20.04
#Setup Environment
ENV BOTFileName index.js
VOLUME ["/mnt/bot"]
WORKDIR /mnt/bot

#Install Deps
RUN apt-get update && apt-get -y install sudo
RUN sudo apt update
RUN sudo apt -y install curl dirmngr apt-transport-https lsb-release ca-certificates
RUN curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN sudo apt update

RUN echo "Installed Dependancies"

#Run Bot
CMD node ${BOTFileName}
