FROM ubuntu:18.04
#Setup Environment
ENV BOTFileName index.js
VOLUME ["/mnt/bot"]
WORKDIR /mnt/bot

#Install Deps
RUN apt-get update && apt-get -y install sudo
RUN curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN sudo apt update

RUN echo "Installed Dependancies"

#Run Bot
CMD node ${BOTFileName}
