FROM ubuntu:18.04
#Setup Environment
ENV BOTFileName index.js
VOLUME ["/mnt/bot"]
WORKDIR /mnt/bot

#Install Deps
RUN apt-get update && apt-get -y install sudo
RUN sudo apt-get install -y software-properties-common
RUN sudo apt-add-repository ppa:chris-lea/node.js-legacy
RUN sudo apt-get update 
RUN sudo apt-get install -y nodejs
RUN sudo apt update

RUN echo "Installed Dependancies"

#Run Bot
CMD node ${BOTFileName}
